export const actionTypes = {
    ADD_FILM: "ADD_FILM",
    FETCH_FILMS: "FETCH_FILMS",
    SET_SELECTED_DATE: "SET_SELECTED_DATE",
    SET_SELECTED_FILM: "SET_SELECTED_FILM",
    HIDE_FILM_DETAILS: "HIDE_FILM_DETAILS",
    SHOW_FILM_DETAILS: "SHOW_FILM_DETAILS",
}